spring:
  datasource:
    maximum-pool-size: 10
    minimum-idle: 3
    idle-timeout: 30000
    connection-timeout: 2000
    max-lifetime: 1800000
    url: jdbc:postgresql://localhost:5432/easydiet
    username: easydiet
    password: easydiet
    driver-class-name: org.postgresql.Driver
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 200

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    secret: lOttCoe01vtAQv6jYe74mTG/w0VGkRTBZJtFBp+HlfI=
    expiration: 3600
  refresh:
    expiration-days: 14
